language: php

sudo: false

php:
  - 7.0
  - nightly

before_script:
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit
  - vendor/bin/phpdoccheck -d ./app/ --skip-classes
