language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit
